### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by alex-page** [govau/chameleon#14]
Test the whole process from starting the server, sending a request and receiving some HTML.

**Comment by adamzerella** [comment]
We've got some good integration testing going now, check it out. 

We have an issue with reading a large fixture file though, `fs.readFileSync` doesn't seem too great at this, see: https://stackoverflow.com/questions/25783161/asserting-files-that-have-the-same-content

**Comment by adamzerella** [comment]
@alex-page Nice, we'll switch to a hashing fixture model :)

**Comment by adamzerella** [comment]
Implemented with #31
