### ISSUE TITLE
Page form loads defaults from _globals.scss

### ISSUE THREAD

**Issue by adamzerella** [govau/chameleon#15]
On page load the form should load the default variable value for the values we map.

E.g:

`$AU-color-foreground-text: #313131` as a default so the form will read 

`Text: #313131`

**Comment by alex-page** [comment]
Interesting approach!

My original thinking was to just show the default colours with an empty form. I like this idea but I thought an empty form would be easier to do. What do you think?

**Comment by adamzerella** [comment]
Empty form meaning, just set the default value to what we usually use for that field ?

**Comment by alex-page** [comment]
My template HTML is a bit broken, so please ignore that. However you can see an empty form and a default page template being loaded. In contains the sass file converted to css without any query parameters or colours entered in.

<img width="500" alt="screen shot 2018-11-23 at 11 37 06 am" src="https://user-images.githubusercontent.com/19199063/48925111-3f965000-ef14-11e8-8ed0-3be1fac6b960.png">

**Comment by adamzerella** [comment]
Ahh gotcha, good idea.

I think later on we should show the user what the default values are though, maybe just a quick mention somewhere? Maybe just link them to the core module?
