### ISSUE TITLE
nodemon is used in production

### ISSUE THREAD

**Issue by alex-page** [govau/chameleon#28]
`nodemon` is useful for local development when we want to refresh our server as we make changes. We probably want to just `npm run start` which runs `node index.js`. It is also a developer dependency. Maybe we should just make it run `nodemon` on `npm run watch`.

**Comment by adamzerella** [comment]
Resolved by changing scripts to `start: node src/index.js` and `dev: nodemon ...`.

This was never deploying with `nodemon` in prod though

**Comment by alex-page** [comment]
Good to know, however `npm run start` is usually ran in node containers so best practice to seperate it. The task for `nodemon` is usually `npm run watch` as it runs it and watches for changes.
