### ISSUE TITLE
Remove Sync funcitons for async

### ISSUE THREAD

**Issue by alex-page** [govau/chameleon#36]

**Comment by adamzerella** [comment]
This would include, moving asynchronous code outside of functions that do not need to be asynchronous. 

For example GenerateHTML could take the errors and <style> from GenerateCSS and it doesn't need to be async.

That being said GenerateHTML will probably use async file reading, that being said it should be seperated from GenerateCSS.

**Comment by alex-page** [comment]
Going to be important:
https://stackoverflow.com/questions/17604866/difference-between-readfile-and-readfilesync

**Comment by adamzerella** [comment]
Merged
