### ISSUE TITLE
Investigate Base64 encoding of URL

### ISSUE THREAD

**Issue by adamzerella** [govau/chameleon#5]
This will help with shortening and sharing the URL, makes it look nicer.

**Comment by alex-page** [comment]
This will be an interesting one. I experimented with it briefly.

Some things to consider:
- Strip white space
- Consider making the keys smaller or just using an ordered array
- We don't really want to save unique id's anywhere so this might make the URL quite long.
- I like this example ( watch the url ): https://github.com/seek-oss/playroom/raw/master/images/demo.gif?raw=true

**Comment by alex-page** [comment]
I am going to close this issue as we are working on a seperate one for design systems:
https://github.com/govau/designsystem/issues/361

**Comment by adamzerella** [comment]
After some investigating it appears that we can do this easily with the https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding `atob` and `dtoa` JS functions over something like `CryptoJS`. 

However, it's not going to be possible to shorten the query string AND decrypt / decode it at the same time. Hashes like MD5 and SHA1 and produce a one way cryptographic result, we'd be looking for a cipher here like AES / DES to encrypt / decrypt but the problem of encoding / encrypting and shortening is not possible.

**Comment by alex-page** [comment]
Nice work @adamzerella I definitely learned something today!
