### ISSUE TITLE
Make sure the colours submitted are actually colours

### ISSUE THREAD

**Issue by adamzerella** [govau/chameleon#7]
Basic error checking ( server side preferably ), did the user submit a valid color code? 

Do we accept HSL and RGBA or just code / hex ?

**Comment by alex-page** [comment]
This could actually happen with sass, it will throw an error when compiling the css if the color is invalid. How you display that error back to the user will be interesting.

**Comment by adamzerella** [comment]
Temporary solution for URI decoding: https://github.com/govau/chameleon/pull/19

Now we just need to inform the user that their color value is malformed, possibly just rendering a "error" page inside the iframe ? `Ruh roe! it appears you've entered a malformed color value.`
