### ISSUE TITLE
Unit tests for functionality

### ISSUE THREAD

**Issue by adamzerella** [govau/chameleon#8]
Basic express mock route stuff, when user hits url, does it send back HTML ?

**Comment by alex-page** [comment]
I would see this as unit testing functions. We should be writing clean functions that are testable and repeatable.
- Convert sass -> css
- Replace css in html file

Mocking express I would see as an integration test as you are testing the whole experience of connecting to the server.

**Comment by adamzerella** [comment]
I think we should close this for now and technically have these tests in the designsystem site, thoughts?

**Comment by alex-page** [comment]
We discussed this, there is some functionality we can break up and test!
