### ISSUE TITLE
Unable to handle completely encoded query string

### ISSUE THREAD

**Issue by adamzerella** [govau/chameleon#91]
It seems that we've only tested for encoding colors with`#` when handling the querystring, Chameleon is currently unable parse a completely encoded URL like: 

http://localhost:8080/templates/home/customise/%3Faction%3D%23026540%26focus%3D%23ac1523

compared with: 

http://localhost:8080/templates/home/customise/?action=%23026540&focus=%23ac1523

**Comment by alex-page** [comment]
I disagree with this issue, it should only be encoding the values of the colours. Chameleon should work with default form submission encoding, which is the second link.
